// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MessangerClient is the client API for Messanger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessangerClient interface {
	SendMessage(ctx context.Context, in *DefaultMessage, opts ...grpc.CallOption) (*DefaultMessage, error)
}

type messangerClient struct {
	cc grpc.ClientConnInterface
}

func NewMessangerClient(cc grpc.ClientConnInterface) MessangerClient {
	return &messangerClient{cc}
}

func (c *messangerClient) SendMessage(ctx context.Context, in *DefaultMessage, opts ...grpc.CallOption) (*DefaultMessage, error) {
	out := new(DefaultMessage)
	err := c.cc.Invoke(ctx, "/Messanger/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessangerServer is the server API for Messanger service.
// All implementations must embed UnimplementedMessangerServer
// for forward compatibility
type MessangerServer interface {
	SendMessage(context.Context, *DefaultMessage) (*DefaultMessage, error)
	mustEmbedUnimplementedMessangerServer()
}

// UnimplementedMessangerServer must be embedded to have forward compatible implementations.
type UnimplementedMessangerServer struct {
}

func (UnimplementedMessangerServer) SendMessage(context.Context, *DefaultMessage) (*DefaultMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedMessangerServer) mustEmbedUnimplementedMessangerServer() {}

// UnsafeMessangerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessangerServer will
// result in compilation errors.
type UnsafeMessangerServer interface {
	mustEmbedUnimplementedMessangerServer()
}

func RegisterMessangerServer(s grpc.ServiceRegistrar, srv MessangerServer) {
	s.RegisterService(&Messanger_ServiceDesc, srv)
}

func _Messanger_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefaultMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessangerServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Messanger/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessangerServer).SendMessage(ctx, req.(*DefaultMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// Messanger_ServiceDesc is the grpc.ServiceDesc for Messanger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Messanger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Messanger",
	HandlerType: (*MessangerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _Messanger_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/message/message.proto",
}
